### ISSUE TITLE
Сделать API для всех функций и разрешения

### ISSUE THREAD

**Issue by CodeGenTeam** [CodeGenTeam/volcenter#2]
то есть реализовать CRUD для всех таблиц в migrations. Для того, чтобы администратор мог с ними работать. Для пользователя разрешать только то, что для него. Он не может вмешиваться в редактирование мероприяти и т.д. Система сама записывает события, происходящие с ним.
пример: volcenter/app/Http/Controllers/API/APIEventTypeController.php
Подумать по поводу проверки `if ($request->ajax())
        {
            /*Some code*/
        }`, запретить обращаться напрямую к запросам, только через ajax запросы. Можно ли это обойти и как защититься в таком случае.
Документация по разрешениям: https://workflowy.com/s/FuFjAIvkuV

Делается параллельно с #3

**Comment by Dualse** [comment]
Можно же midleware сделать, и повесить на нужный контроллер. Она будет отсекать.

**Comment by CodeGenTeam** [comment]
@Dualse Отличная идея. Тогда стоит подумать на permissions, там реализовано это
