### ISSUE TITLE
PermissionController ошибка с не admin группой пользователя

### ISSUE THREAD

**Issue by CodeGenTeam** [CodeGenTeam/volcenter#8]
$group->name
если у меня есть правило *, но я не админ, то не пропускает, так как user. ошибка
ErrorException in PermissionController.php line 31:
Undefined index: user

https://github.com/CodeGenTeam/volcenter/blob/master/app/AdminPanel/Controllers/pex/PermissionController.php#L23

**Comment by AlexP9712** [comment]
![default](https://cloud.githubusercontent.com/assets/1575858/16173620/de673826-35c0-11e6-8adc-505173f55b57.PNG)
?

**Comment by CodeGenTeam** [comment]
Это единичная проблема, после того как обновляется страница, ошибка исчезает

**Comment by CodeGenTeam** [comment]
Там запрос при первом обращении идет и создается группа, а после она уже есть и ошибки нету

**Comment by AlexP9712** [comment]
Ну тогда эта проблема закрыта))
Так как группы генерятся сиддераом, который ты проигнорил)
